# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check build.gradle files instead.

# When configured, Gradle will run in offline mode and will not download any dependencies from the internet.
# offline=true

# The Kotlin version to use for building.
kotlin.code.style=official

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include resources from the
# dependencies of the library. Placing the library in the same namespace as the app
# would change its R class to include resources from app as well.
# android.nonTransitiveRClass=true
